### ISSUE TITLE
How to get image information?

### ISSUE THREAD

**Issue by Alan-Py** [noahcao/animal-pose-dataset#6]
In your googleDrive I can only find json file. How to get image data for this dataset.

**Comment by Alan-Py** [comment]
OK, I can find PASCALVOC image in your dataset, but can you tell me how to find do32.jpeg co99.jpeg? I can't match the name you define with Animal 10.

**Comment by DareFail** [comment]
I have the same problem, where did you find any of them?

> OK, I can find PASCALVOC image in your dataset, but can you tell me how to find do32.jpeg co99.jpeg? I can't match the name you define with Animal 10.

**Comment by noahcao** [comment]
Hi,

I removed the original version of `images.zip` file by accident in that google drive folder. Please refer to the stock [here](https://drive.google.com/drive/folders/1DwhQobZlGntOXxdm7vQsE4bqbFmN3b9y?usp=drive_link) for the images outside PASCAL dataset.

I will later better organize the files and update the images info. Sorry for the confusion.

**Comment by DareFail** [comment]
Oh awesome! thanks

**Comment by Alan-Py** [comment]
> 你好，
> 
> 我意外地删除了该google驱动器文件夹中文件的原始版本。有关PASCAL数据集之外的图像，请参阅[此处的](https://drive.google.com/drive/folders/1DwhQobZlGntOXxdm7vQsE4bqbFmN3b9y?usp=drive_link)`images.zip`库存。[](https://drive.google.com/drive/folders/1DwhQobZlGntOXxdm7vQsE4bqbFmN3b9y?usp=drive_link)
> 
> 我稍后会更好地整理文件并更新图片信息。以免造成混乱。

nice, I solve this problem, thank you!
